zn "%SYS"
write $zversion,!
set properties("Password")="WaypointLocal-2026!",properties("ChangePassword")=0
set $ETRAP="write $ZERROR,! do $SYSTEM.Process.Terminate($JOB,1)" set sc=##class(Security.Users).Modify("SuperUser",.properties) if $SYSTEM.Status.IsError(sc) do $SYSTEM.Status.DisplayError(sc) do $SYSTEM.Process.Terminate($JOB,1)
set app("Enabled")=1,app("AutheEnabled")=32
set $ETRAP="write $ZERROR,! do $SYSTEM.Process.Terminate($JOB,1)" set sc=##class(Security.Applications).Modify("/api/admin",.app) if $SYSTEM.Status.IsError(sc) do $SYSTEM.Status.DisplayError(sc) do $SYSTEM.Process.Terminate($JOB,1)
halt
