/** IRIS 2026.2 requires the complete Task record on creation, including unused fields. */
export function taskDefaults(username: string) {
  return {
    Name: '',
    RunAsUser: username,
    EmailOnCompletion: [],
    EmailOnError: [],
    EmailOnExpiration: [],
    EmailOutput: false,
    Expires: false,
    ExpiresDays: 0,
    ExpiresHours: 0,
    ExpiresMinutes: 0,
    OpenOutputFile: false,
    OutputDirectory: '',
    OutputFilename: '',
    OutputFileIsBinary: false,
    SuspendOnError: true,
    SuspendTerminated: true,
    Priority: 'Normal',
    TaskClass: '',
    IsBatch: false,
    NameSpace: '%SYS',
    TimePeriod: 'On Demand',
    TimePeriodEvery: '',
    TimePeriodDay: '',
    DailyFrequency: 'Once',
    DailyFrequencyTime: '',
    DailyIncrement: '',
    DailyStartTime: '00:00:00',
    DailyEndTime: '00:00:00',
    StartDate: new Date(Date.now() + 86400000).toISOString().slice(0, 10),
    EndDate: '',
    RunAfterGUID: '',
    MirrorStatus: 'Any',
    RescheduleOnStart: true,
    Description: '',
    Settings: {},
  };
}
